name: schema_build
description: "A professional Server-Driven UI (SDUI) engine and visual builder for Flutter. Create, manage, and update dynamic layouts in real-time via JSON with zero-rebuild reactivity."
version: 0.1.1
homepage: https://github.com/jheimes-silveira/schema_build
repository: https://github.com/jheimes-silveira/schema_build
issue_tracker: https://github.com/jheimes-silveira/schema_build/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
